### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by GilesBathgate** [BartoszMilewski/CodeCoop#1]
@BartoszMilewski Would you be so kind as to upload the various binaries somewhere accessible? 

Specifically, it would be useful to have:
`ftp://ftp.relisoft.com/cmdline.exe`

Making the others available in the github releases area of the project would also be helpful.

**Comment by BartoszMilewski** [comment]
I moved away from C++. I don't even have a compiler any more.

**Comment by GilesBathgate** [comment]
@BartoszMilewski I thought you might have a backup of the files on FTP. No worries, we will have to find another way.
