### ISSUE TITLE
Migrating a Code Co-op project to git

### ISSUE THREAD

**Issue by SGupta-TMSI** [BartoszMilewski/CodeCoop#2]
@BartoszMilewski Hi, Have you ever tried to migrate a Code Co-op project to git so that it includes all the history as well?

**Comment by BartoszMilewski** [comment]
I haven't touched this project for decades, and I'm not planning to do it. I'm not even sure if it comples any more. You might see copyright notices in source files, but it's really public domain now, so feel free to use it in any way you want.

**Comment by SGupta-TMSI** [comment]
OK. Thanks for the quick response.

**Comment by bassklampfe** [comment]
@SGupta-TMSI : May I point to my (very old) project [CodeCoop2Svn](https://github.com/bassklampfe/CodeCoop2Svn)
Although it might be not the shortest way you could try
CodeCoop -> [via CodeCoop2Svn] -> subversion -> [via any known tool] -> git
This should include all history also in the final git repository
